"""Add AuditLog table

Revision ID: 45229dfec1f2
Revises: 6dea6ac4fb9e
Create Date: 2026-03-03 02:07:46.132913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45229dfec1f2'
down_revision = '6dea6ac4fb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('target_user', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
