"""Add description column to Task model and new vuln endpoints

Revision ID: db59fb970b54
Revises: ef2c55c2156d
Create Date: 2026-04-06 09:48:57.773601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db59fb970b54'
down_revision = 'ef2c55c2156d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
