"""Add target_project column to audit_logs.

Revision ID: ef2c55c2156d
Revises: 2bd167436f96
Create Date: 2026-03-21 11:15:30.952650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2c55c2156d'
down_revision = '2bd167436f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_project', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('target_project')

    # ### end Alembic commands ###
